name: weather_app
description: "Weather Flutter app."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+3

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  injectable: ^2.3.2
  json_annotation: ^4.8.1
  dartz: ^0.10.1
  dio: ^5.4.0
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  routemaster: ^1.0.1
  intl: ^0.19.0
  connectivity_plus: ^6.0.5
  mocktail: ^1.0.1
  equatable: ^2.0.5
  bloc_test: ^9.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:
  injectable_generator:
  flutter_lints: ^4.0.0
  integration_test:
    sdk: flutter

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/icons/
